@server = http://localhost:3000

### GET All
GET {{server}}/blog

### POST
POST {{server}}/blog
Content-Type: application/json

{
  "title": "Title",
  "content": "Content",
  "name": "Name"
}

### GET <게시글ID> 값 변경해 사용
GET {{server}}/blog/1

### DELETE <게시글ID> 값 변경해 사용
DELETE {{server}}/blog/3

### PUT <게시글ID> 값과 json 값 변경해 사용
PUT {{server}}/blog/2
Content-Type: application/json

{
  "title": "Update",
  "content": "Content",
  "name": "Arthur"
}
